config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get '/about', to: 'about#index', as: :about
  get '/story', to: 'story#index', as: :story
  get '/get_involved', to: 'get_involved#index', as: :get_involved
  get '/volunteer', to: 'volunteer#index', as: :volunteer
  get '/donate', to: 'donate#index', as: :donate
  get '/programs', to: 'programs#index', as: :programs
  get '/garden', to: 'garden#index', as: :garden
  get '/pumpkin_smash', to: 'pumpkin_smash#index', as: :pumpkin_smash
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/donate_controller.rb
class DonateController < ApplicationController
  def index; end
end

app/controllers/garden_controller.rb
class GardenController < ApplicationController
  def index; end
end

app/controllers/get_involved_controller.rb
class GetInvolvedController < ApplicationController
  def index; end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  def index; end
end

app/controllers/story_controller.rb
class StoryController < ApplicationController
  def index; end
end

app/controllers/volunteer_controller.rb
class VolunteerController < ApplicationController
  def index; end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_link?(path)
    return 'active' if current_page?(path)

    nil
  end
end

app/helpers/donate_helper.rb
module DonateHelper
end

app/helpers/garden_helper.rb
module GardenHelper
end

app/helpers/get_involved_helper.rb
module GetInvolvedHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/pumpkin_smash_helper.rb
module PumpkinSmashHelper
end

app/helpers/story_helper.rb
module StoryHelper
end

app/helpers/volunteer_helper.rb
module VolunteerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scraps to Soil</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.png' %>
    <link href="https://fonts.googleapis.com/css?family=Lato|Merienda|Arvo|Raleway" rel="stylesheet">
  </head>

  <body>
    <%= render 'partials/header' %>
    <div class="content">
      <%= yield %>
    </div>
    <%= render 'partials/footer' %>
  </body>
</html>

app/views/partials/_footer.html.erb
<div class="footer">
  <div class="container footer_1">
    <div class="background"></div>
    <div class="footer_content">
      <p>
        <a href="tel:3039008716">(303) 900-8716</a>
        <br />
        <a href="mailto:info@scraps-to-soil.org">info@scraps-to-soil.org</a>
      </p>
    </div>
  </div>
  <div class="container footer_2">
    <div class="background"></div>
    <div class="footer_content">
      <p>
        copyright <%= Date.today.year %>, s2s is a 501c3
      </p>
    </div>
  </div>
  <div class="container footer_3">
    <div class="background"></div>
    <div class="footer_content">
      <ul>
        <li>
          Strengthen and protect ecosystem health and biodiversity
        </li>
        <li>
          Breakdown barriers and foster support for the young farmers entering the profession
        </li>
        <li>
          Protect public health, human communities and or animal welfare
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/partials/_header.html.erb
<div class="header">
  <div class="nav_links">
    <ul>
      <li>
        <%= link_to 'Home', root_path, id: :home, class: active_link?(root_path) %>
      </li>
      <li>
        <%= link_to 'Get Involved', get_involved_path, id: :get_involved, class: active_link?(get_involved_path) || active_link?(volunteer_path) || active_link?(donate_path) %>
        <ul class="submenu">
          <li>
            <%= link_to 'Volunteer', volunteer_path, id: :volunteer %>
          </li>
          <li>
            <%= link_to 'Donate', donate_path, id: :donate %>
          </li>
        </ul>
      </li>
    </ul>
  </div>
  <%= image_tag 'logo_green.png', class: :logo %>
  <div class="nav_links">
    <ul>
      <li>
        <%= link_to 'About', about_path, id: :about, class: active_link?(about_path) %>
      </li>
      <li>
        <%= link_to 'Story', story_path, id: :story, class: active_link?(story_path) %>
      </li>
      <li>
        <%= link_to 'Programs', programs_path, id: :programs, class: active_link?(programs_path) || active_link?(pumpkin_smash_path) || active_link?(garden_path) %>
        <ul class="submenu">
          <li>
            <%= link_to 'Garden', garden_path, id: :garden %>
          </li>
          <li>
            <%= link_to 'Pumpkin Smash', pumpkin_smash_path, id: :pumpkin_smash %>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</div>

app/views/partials/_title.html.erb
<%= image_tag 'soil_cropped_2.jpg', class: 'splash' %>
<div class="title">
  <h1><%= title %></h1>
</div>